version: 0.2

phases:
  install:
    commands:
      - python -m pip install --upgrade pip build awscli

  build:
    commands:
      - cd lambda/imf
      - python -m build --wheel
      - aws s3 cp dist/*.whl s3://ecolooker-artifacts/imf/ --region us-east-2